using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Media;
using Forms = System.Windows.Forms;
using WpfApplication = System.Windows.Application;
using WpfBinding = System.Windows.Data.Binding;
using WpfButton = System.Windows.Controls.Button;
using WpfCheckBox = System.Windows.Controls.CheckBox;
using WpfComboBox = System.Windows.Controls.ComboBox;
using WpfProgressBar = System.Windows.Controls.ProgressBar;
using WpfTextBox = System.Windows.Controls.TextBox;
namespace LocalLlmConsole;

public partial class MainWindow
{
    private const string AppDisplayName = "llama.cpp Console";
    private const string AppVersionLabel = "v1.0";

    private sealed record RuntimeUpdateCheck(bool IsInstalled, bool HasUpdate, string LocalCommit, string RemoteCommit);
    private sealed record RuntimeMetricDisplaySnapshot(
        string RuntimeKey,
        IReadOnlyList<PrometheusSample> Samples,
        string GenerationRate,
        string TotalTokens,
        string Settings,
        DateTimeOffset CapturedAt);

    private readonly string _workspaceRoot;
    private StateStore? _stateStore;
    private LocalAppService? _service;
    private JobEngine? _jobs;
    private ModelCatalogService? _catalog;
    private RuntimeRegistryService? _runtimes;
    private HuggingFaceService? _huggingFace;
    private OpenCodeConfigService? _openCode;
    private readonly AppUpdateService _appUpdates = new();
    private readonly WslEnvironmentService _wslEnvironment = new();
    private readonly ActiveRuntimeSessionStore _activeSessions;
    private readonly TrackedProcessRunner _processRunner = new();
    private readonly LlamaProcessSupervisor _llama = new();
    private readonly MainWindowViewModel _viewModel = new();
    private AppSettings _settings;
    private AppSettings? _activeRuntimeSettings;
    private OpenCodeFileSet _openCodeFiles = new("", "");

    private readonly HashSet<string> _autoScannedRuntimeRoots = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, RuntimeUpdateState> _runtimeUpdateStates = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, CancellationTokenSource> _runtimeBuildCancellations = new(StringComparer.OrdinalIgnoreCase);
    private readonly object _wslBuildMarkerGate = new();
    private readonly HashSet<string> _activeWslBuildMarkers = new(StringComparer.OrdinalIgnoreCase);
    private WpfComboBox? _runtimeCombo;
    private TextBlock? _modelCapabilityText;
    private WpfTextBox? _contextSizeBox;
    private WpfTextBox? _gpuLayersBox;
    private WpfTextBox? _parallelSlotsBox;
    private WpfTextBox? _batchSizeBox;
    private WpfTextBox? _microBatchSizeBox;
    private WpfTextBox? _threadsBox;
    private WpfTextBox? _reasoningBudgetBox;
    private WpfTextBox? _temperatureBox;
    private WpfTextBox? _topKBox;
    private WpfTextBox? _topPBox;
    private WpfTextBox? _minPBox;
    private WpfTextBox? _maxTokensBox;
    private WpfTextBox? _seedBox;
    private WpfTextBox? _repeatLastNBox;
    private WpfTextBox? _repeatPenaltyBox;
    private WpfTextBox? _presencePenaltyBox;
    private WpfTextBox? _frequencyPenaltyBox;
    private WpfComboBox? _metricsCombo;
    private WpfComboBox? _themeCombo;
    private WpfComboBox? _reasoningCombo;
    private WpfComboBox? _reasoningFormatCombo;
    private WpfComboBox? _visionCombo;
    private WpfTextBox? _visionImageMinTokensBox;
    private WpfTextBox? _visionImageMaxTokensBox;
    private WpfComboBox? _flashAttentionCombo;
    private WpfComboBox? _cacheTypeKCombo;
    private WpfComboBox? _cacheTypeVCombo;
    private WpfComboBox? _kvOffloadCombo;
    private WpfComboBox? _kvUnifiedCombo;
    private WpfComboBox? _continuousBatchingCombo;
    private WpfComboBox? _jinjaCombo;
    private WpfComboBox? _mmapCombo;
    private WpfComboBox? _mlockCombo;
    private WpfComboBox? _ropeScalingCombo;
    private WpfTextBox? _ropeScaleBox;
    private WpfTextBox? _ropeFreqBaseBox;
    private WpfTextBox? _ropeFreqScaleBox;
    private WpfComboBox? _speculativeTypeCombo;
    private WpfTextBox? _specDraftModelPathBox;
    private WpfTextBox? _specDraftGpuLayersBox;
    private WpfTextBox? _specDraftMinTokensBox;
    private WpfTextBox? _specDraftMaxTokensBox;
    private WpfTextBox? _specDraftPSplitBox;
    private WpfTextBox? _specDraftPMinBox;
    private WpfComboBox? _specDraftCacheTypeKCombo;
    private WpfComboBox? _specDraftCacheTypeVCombo;
    private WpfTextBox? _hfQueryBox;
    private WpfTextBox? _logsBox;
    private DataGrid? _logsGrid;
    private WpfButton? _loadModelButton;
    private WpfButton? _restartModelButton;
    private WpfButton? _unloadModelButton;
    private WpfButton? _saveModelLaunchSettingsButton;
    private DataGrid? _modelsGrid;
    private DataGrid? _runtimeGrid;
    private DataGrid? _runtimeBuildGrid;
    private DataGrid? _runtimeJobsGrid;
    private DataGrid? _wslDistroGrid;
    private DataGrid? _runtimeMetricsGrid;
    private DataGrid? _lifetimeMetricsGrid;
    private WpfComboBox? _overviewModelCombo;
    private WpfComboBox? _openCodeModelCombo;
    private WpfComboBox? _openCodeLocalModelCombo;
    private WpfComboBox? _openCodeAgentCombo;
    private WpfComboBox? _openCodeAgentKindCombo;
    private WpfTextBox? _openCodeModelSnippetBox;
    private WpfTextBox? _openCodeAgentSnippetBox;
    private WpfTextBox? _openCodeNewAgentNameBox;
    private TextBlock? _openCodeConfigPathText;
    private TextBlock? _openCodeAgentsPathText;
    private TextBlock? _openCodeAddModelStatusText;
    private FrameworkElement? _openCodeAddModelPanel;
    private FrameworkElement? _openCodeAddAgentPanel;
    private WpfButton? _openCodeSaveModelButton;
    private WpfButton? _openCodeDeleteModelButton;
    private WpfButton? _openCodeAddLocalModelButton;
    private WpfButton? _openCodeUpdateLocalModelButton;
    private WpfButton? _openCodeAddAsNewLocalModelButton;
    private WpfButton? _openCodeSaveAgentButton;
    private WpfButton? _openCodeDeleteAgentButton;
    private WpfButton? _openCodeCreateAgentButton;
    private bool _updatingOpenCodeModelEditor;
    private string _openCodeSelectedModelSnapshot = "";
    private WpfButton? _overviewLoadButton;
    private WpfButton? _overviewUnloadButton;
    private DataGrid? _hfGrid;
    private DataGrid? _downloadHistoryGrid;
    private System.Windows.Threading.DispatcherTimer? _downloadHistoryTimer;
    private System.Windows.Threading.DispatcherTimer? _runtimeDashboardTimer;
    private bool _hfShowingDownloadHistory;
    private bool _downloadHistoryRefreshInFlight;
    private bool _runtimeDashboardRefreshInFlight;
    private WpfTextBox? _overviewRuntimeLogBox;
    private Grid? _runtimeDashboardModel;
    private Grid? _runtimeDashboardRuntime;
    private Grid? _runtimeDashboardGenerationRate;
    private Grid? _runtimeDashboardTotalTokens;
    private Grid? _runtimeDashboardRequests;
    private Grid? _runtimeDashboardGpu;
    private Grid? _wslStatusMetric;
    private Grid? _wslSelectedMetric;
    private Grid? _wslInfoMetric;
    private Grid? _wslToolsMetric;
    private bool _wslLinuxAutoRefreshDone;
    private WpfButton? _wslInstallButton;
    private WpfButton? _wslCheckUpdatesButton;
    private WpfButton? _wslDeleteButton;
    private WpfButton? _wslInstallUbuntuButton;
    private WpfButton? _wslInstallBuildToolsButton;
    private WpfButton? _wslInstallCudaToolkitButton;
    private WpfButton? _wslInstallVulkanToolsButton;
    private WpfButton? _wslCheckUbuntuUpdatesButton;
    private WpfButton? _wslDeleteUbuntuButton;
    private WpfButton? _wslDeleteBuildToolsButton;
    private WpfButton? _wslDeleteCudaToolkitButton;
    private WpfButton? _wslDeleteVulkanToolsButton;
    private WpfProgressBar? _runtimeDashboardModelProgress;
    private TextBlock? _modelsFolderText;
    private TextBlock? _runtimesFolderText;
    private readonly HttpClient _metricsClient = new() { Timeout = TimeSpan.FromSeconds(2) };
    private readonly Dictionary<string, List<FrameworkElement>> _launchSettingElements = new(StringComparer.OrdinalIgnoreCase);
    private readonly List<FrameworkElement> _advancedLaunchSections = new();
    private readonly Dictionary<string, ModelCapabilitySummary> _modelCapabilityCache = new(StringComparer.OrdinalIgnoreCase);
    private ModelCapabilitySummary _selectedModelCapabilities = ModelCapabilityService.Empty();
    private WpfCheckBox? _advancedLaunchSettingsToggle;
    private bool _showAdvancedLaunchSettings;
    private string _launchSettingsModelId = "";
    private ModelLaunchSettings? _savedLaunchSettingsSnapshot;
    private bool _hasSavedLaunchSettingsSnapshot;
    private bool _updatingLaunchSettingsControls;
    private string _lastMetricRuntimeKey = "";
    private double? _lastPredictedTokenCounter;
    private double? _lastPromptTokenCounter;
    private DateTimeOffset? _lastMetricPollAt;
    private string _lastSlotRuntimeKey = "";
    private double? _lastSlotPromptProcessedCounter;
    private double? _lastSlotGeneratedCounter;
    private DateTimeOffset? _lastSlotPollAt;
    private RuntimeMetricDisplaySnapshot? _lastRuntimeMetricDisplay;
    private string _lastLifetimeRuntimeKey = "";
    private double? _lastLifetimePromptCounter;
    private double? _lastLifetimeGeneratedCounter;
    private string _lastIdleRuntimeKey = "";
    private double? _lastIdlePromptCounter;
    private double? _lastIdleGeneratedCounter;
    private DateTimeOffset? _lastRuntimeActivityAt;
    private bool _autoUnloadInProgress;
    private string _cachedGpuSummary = "Unavailable";
    private DateTimeOffset _cachedGpuSummaryAt = DateTimeOffset.MinValue;
    private bool _pageHostEnabledBeforeBusy = true;
    private System.Windows.Threading.DispatcherTimer? _modelLoadingTimer;
    private System.Windows.Threading.DispatcherTimer? _modelLoadedStatusTimer;
    private DateTimeOffset _modelLoadingStartedAt;
    private string _modelLoadingModelName = "";
    private string _modelLoadingEndpoint = "";
    private string _modelLoadedStatusText = "";
    private bool _shutdownRequested;
    private bool _shutdownCleanupComplete;
    private Forms.NotifyIcon? _trayIcon;
    private WindowState _windowStateBeforeTray = WindowState.Normal;
    private bool _minimizingToTray;
    private bool _shownTrayHint;
    private CancellationTokenSource? _runtimeReadinessCts;
    private CancellationTokenSource? _launchSettingsRefreshCts;
    private string _helpFocusTarget = "";
}
